# Generated by Django 3.2.9 on 2021-11-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='address_bsc',
            field=models.CharField(default='Адрес в сети Binance Smart Chain - Testnet', max_length=255),
        ),
    ]
